# -*- coding: utf-8 -*-
"""english_to_french_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOkvXgWxbqIvF3W7sqQIrsFgSbOyOI2Y
"""

# english to french translation chatbot

!pip install -q transformers sentencepiece

import time
import sys

from transformers import MarianMTModel, MarianTokenizer

# translation model
MODEL_NAME = "Helsinki-NLP/opus-mt-en-fr"

# loading tokenizer and model
tokenizer = MarianTokenizer.from_pretrained(MODEL_NAME)

model = MarianMTModel.from_pretrained(MODEL_NAME)

# translation function

def translate_to_french(english_text):

    tokens = tokenizer([english_text], return_tensors="pt", padding=True)

    translated_tokens = model.generate(**tokens)

    french_text = tokenizer.decode(
        translated_tokens[0],
        skip_special_tokens=True
    )

    return french_text

# quick test
test = translate_to_french("Hello world")
print(test)

# typing effect

def typing_effect(text, delay=0.03):

    for char in text:

        sys.stdout.write(char)
        sys.stdout.flush()

        time.sleep(delay)

    print()


typing_effect("Bonjour, ceci est un test.")

# chatbot loop

def run_chatbot():

    print("English to French Translation Chatbot")
    print("Type 'quit' to exit.\n")

    while True:

        user_input = input("You: ").strip()

        if user_input.lower() in ["quit", "exit"]:

            print("Bot: Au revoir!")
            break

        if not user_input:

            print("Enter a message\n")
            continue

        try:

            french = translate_to_french(user_input)

            print("French: ", end="")

            typing_effect(french)

            print()

        except Exception as e:

            print(f"Error: {e}\n")


run_chatbot()

# sample translations

test_sentences = [
    "Good morning! How are you today?",
    "My name is Diya.",
    "I am a mechanical engineering student."
]

for sentence in test_sentences:

    result = translate_to_french(sentence)

    print("EN:", sentence)
    print("FR:", result)
    print()